GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name           | Type  | Params
-----------------------------------------
0 | model_backbone | Model | 2.8 M 
-----------------------------------------
2.8 M     Trainable params
0         Non-trainable params
2.8 M     Total params
11.110    Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
cuda True
NVIDIA GeForce RTX 3090
Model:
 MoleculeModel(
  (model_backbone): Model(
    (atom_preprocess): ModuleList(
      (0): AtomEdgeInteraction(
        (interaction): Linear(in_features=147, out_features=128, bias=True)
      )
      (1-8): 8 x Sequential(
        (0): Linear(in_features=128, out_features=128, bias=True)
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): PReLU(num_parameters=1)
        (3): Dropout(p=0.0, inplace=False)
      )
    )
    (sage_convolutions): ModuleList(
      (0): SAGEConv(128, 1024, aggr=mean)
      (1): SAGEConv(1024, 1024, aggr=mean)
    )
    (postprocess): ModuleList(
      (0-1): 2 x Sequential(
        (0): Linear(in_features=1024, out_features=128, bias=True)
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): PReLU(num_parameters=1)
        (3): Dropout(p=0.0, inplace=False)
      )
    )
    (output_layer): Linear(in_features=128, out_features=1, bias=True)
  )
)
Traceback (most recent call last):
  File "/home/nikolenko/work/gat/sage.py", line 189, in <module>
    trainer.fit(model, data_module)
  File "/home/nikolenko/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/nikolenko/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/nikolenko/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/nikolenko/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
  File "/home/nikolenko/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_stage
    self._run_sanity_check()
  File "/home/nikolenko/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1060, in _run_sanity_check
    val_loop.run()
  File "/home/nikolenko/.local/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/nikolenko/.local/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/nikolenko/.local/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/home/nikolenko/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/nikolenko/.local/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 412, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/home/nikolenko/work/gat/utils/train.py", line 41, in validation_step
    y_hat = self(batch.x, batch.edge_index, batch.edge_attr)
  File "/opt/anaconda3/envs/torch_geom/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nikolenko/work/gat/utils/train.py", line 22, in forward
    return self.model_backbone(x, edge_index, edge_attr)
  File "/opt/anaconda3/envs/torch_geom/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nikolenko/work/gat/sage.py", line 114, in forward
    x = layer(x)
  File "/opt/anaconda3/envs/torch_geom/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/torch_geom/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/opt/anaconda3/envs/torch_geom/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/torch_geom/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (16277x128 and 1024x128)
